# Generated by Django 5.0.4 on 2024-04-15 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sanctioned', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('tenure_start', models.DateField()),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=30)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('club_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.club')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('tenure_start', models.DateField()),
                ('contract_start', models.DateField()),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=30)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.club')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionCoachDelegations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.coach')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.competition')),
                ('delegating_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.PositiveIntegerField()),
                ('stroke', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=20)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.competition')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.club')),
            ],
        ),
        migrations.CreateModel(
            name='GroupCoaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.coach')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPractices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.group')),
            ],
        ),
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=30)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.club')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.TimeField()),
                ('final_time_seconds', models.PositiveIntegerField()),
                ('distance', models.PositiveIntegerField()),
                ('stroke', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=20)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.competition')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.swimmer')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.TimeField()),
                ('final_time', models.PositiveIntegerField()),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.swimmer')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionSwimmersAttending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.competition')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.swimmer')),
            ],
        ),
        migrations.CreateModel(
            name='SwimmerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.group')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamData.swimmer')),
            ],
        ),
    ]
